server:
  address: 'tcp://0.0.0.0:9091/authelia'
  endpoints:
    authz:
      auth-request:
        implementation: 'AuthRequest'

log:
  level: info

ntp:
  disable_startup_check: true
  disable_failure: true

identity_validation:
  reset_password: {}

authentication_backend:
  file:
    path: /config/users_database.yml

access_control:
  default_policy: deny
  rules:
    - domain: '75-hard.garrenmiller.com'
      policy: one_factor

session:
  name: 'authelia_session'
  expiration: 1h
  inactivity: 5m
  cookies:
    - domain: '75-hard.garrenmiller.com'
      authelia_url: 'https://75-hard.garrenmiller.com/authelia/'
      default_redirection_url: 'https://75-hard.garrenmiller.com'

storage:
  local:
    path: /data/db.sqlite3

notifier:
  filesystem:
    filename: /data/notifications.txt

theme: dark
